"""auth e rbac iniciais

Revision ID: 15f27daa52d6
Revises: 
Create Date: 2026-09-01 21:58:51.819253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15f27daa52d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('capabilities',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('domain_slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['domain_slug'], ['domains.slug'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_capabilities_domain_slug'), 'capabilities', ['domain_slug'], unique=False)
    op.create_table('role_bindings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'reviewer', 'domain_expert', 'decision_owner', 'administrator', name='role'), nullable=False),
    sa.Column('domain_slug', sa.String(length=100), nullable=True),
    sa.Column('capability_slug', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['capability_slug'], ['capabilities.slug'], ),
    sa.ForeignKeyConstraint(['domain_slug'], ['domains.slug'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', 'domain_slug', 'capability_slug')
    )
    op.create_index(op.f('ix_role_bindings_user_id'), 'role_bindings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_bindings_user_id'), table_name='role_bindings')
    op.drop_table('role_bindings')
    op.drop_index(op.f('ix_capabilities_domain_slug'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('domains')
    # ### end Alembic commands ###
