"""kernel semantico

Revision ID: 26dc761a9876
Revises: 15f27daa52d6
Create Date: 2026-09-02 05:31:02.980842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '26dc761a9876'
down_revision: Union[str, None] = '15f27daa52d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('atom_id', sa.String(length=300), nullable=True),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_events_atom_id'), 'domain_events', ['atom_id'], unique=False)
    op.create_index(op.f('ix_domain_events_event_type'), 'domain_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_domain_events_occurred_at'), 'domain_events', ['occurred_at'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('repository', sa.String(length=500), nullable=True),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('commit', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('domain_slug', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['domain_slug'], ['domains.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_type'), 'evidence', ['type'], unique=False)
    op.create_table('knowledge_atoms',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('capability', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('classification', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk', sa.String(length=20), nullable=True),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effective', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability'], ['capabilities.slug'], ),
    sa.ForeignKeyConstraint(['domain'], ['domains.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_atoms_capability'), 'knowledge_atoms', ['capability'], unique=False)
    op.create_index(op.f('ix_knowledge_atoms_domain'), 'knowledge_atoms', ['domain'], unique=False)
    op.create_index(op.f('ix_knowledge_atoms_kind'), 'knowledge_atoms', ['kind'], unique=False)
    op.create_index(op.f('ix_knowledge_atoms_status'), 'knowledge_atoms', ['status'], unique=False)
    op.create_table('atom_relations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_atom', sa.String(length=300), nullable=False),
    sa.Column('to_atom', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_atom'], ['knowledge_atoms.id'], ),
    sa.ForeignKeyConstraint(['to_atom'], ['knowledge_atoms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_atom', 'to_atom', 'type')
    )
    op.create_index(op.f('ix_atom_relations_from_atom'), 'atom_relations', ['from_atom'], unique=False)
    op.create_index(op.f('ix_atom_relations_to_atom'), 'atom_relations', ['to_atom'], unique=False)
    op.create_table('evidence_links',
    sa.Column('atom_id', sa.String(length=300), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['atom_id'], ['knowledge_atoms.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('atom_id', 'evidence_id')
    )
    op.create_table('knowledge_atom_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('atom_id', sa.String(length=300), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['atom_id'], ['knowledge_atoms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atom_id', 'rev')
    )
    op.create_index(op.f('ix_knowledge_atom_versions_atom_id'), 'knowledge_atom_versions', ['atom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_atom_versions_atom_id'), table_name='knowledge_atom_versions')
    op.drop_table('knowledge_atom_versions')
    op.drop_table('evidence_links')
    op.drop_index(op.f('ix_atom_relations_to_atom'), table_name='atom_relations')
    op.drop_index(op.f('ix_atom_relations_from_atom'), table_name='atom_relations')
    op.drop_table('atom_relations')
    op.drop_index(op.f('ix_knowledge_atoms_status'), table_name='knowledge_atoms')
    op.drop_index(op.f('ix_knowledge_atoms_kind'), table_name='knowledge_atoms')
    op.drop_index(op.f('ix_knowledge_atoms_domain'), table_name='knowledge_atoms')
    op.drop_index(op.f('ix_knowledge_atoms_capability'), table_name='knowledge_atoms')
    op.drop_table('knowledge_atoms')
    op.drop_index(op.f('ix_evidence_type'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('sources')
    op.drop_index(op.f('ix_domain_events_occurred_at'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_event_type'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_atom_id'), table_name='domain_events')
    op.drop_table('domain_events')
    # ### end Alembic commands ###
