"""confidence e policies

Revision ID: 5a221cf8f7e1
Revises: 26dc761a9876
Create Date: 2026-09-02 05:47:59.584276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5a221cf8f7e1'
down_revision: Union[str, None] = '26dc761a9876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('selector', sa.String(length=200), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=True),
    sa.Column('min_reviewers', sa.Integer(), nullable=True),
    sa.Column('require_owner_approval', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confidence_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('atom_id', sa.String(length=300), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=60), nullable=False),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['atom_id'], ['knowledge_atoms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confidence_scores_atom_id'), 'confidence_scores', ['atom_id'], unique=False)
    op.create_index(op.f('ix_confidence_scores_computed_at'), 'confidence_scores', ['computed_at'], unique=False)
    op.create_table('confidence_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('score_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('explanation', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['score_id'], ['confidence_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confidence_signals_score_id'), 'confidence_signals', ['score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confidence_signals_score_id'), table_name='confidence_signals')
    op.drop_table('confidence_signals')
    op.drop_index(op.f('ix_confidence_scores_computed_at'), table_name='confidence_scores')
    op.drop_index(op.f('ix_confidence_scores_atom_id'), table_name='confidence_scores')
    op.drop_table('confidence_scores')
    op.drop_table('policies')
    # ### end Alembic commands ###
