"""governanca votos comentarios notificacoes

Revision ID: 5c63f0455314
Revises: 5a221cf8f7e1
Create Date: 2026-09-02 05:58:48.913065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c63f0455314'
down_revision: Union[str, None] = '5a221cf8f7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('atom_id', sa.String(length=300), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('atom_id', sa.String(length=300), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['atom_id'], ['knowledge_atoms.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_atom_id'), 'comments', ['atom_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('atom_id', sa.String(length=300), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('role_at_vote', sa.String(length=30), nullable=False),
    sa.Column('is_domain_expert', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['atom_id'], ['knowledge_atoms.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atom_id', 'reviewer_id')
    )
    op.create_index(op.f('ix_votes_atom_id'), 'votes', ['atom_id'], unique=False)
    op.create_index(op.f('ix_votes_reviewer_id'), 'votes', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_reviewer_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_atom_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_comments_atom_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
