"""discovery runs

Revision ID: 5d9c480c8781
Revises: 5c63f0455314
Create Date: 2026-09-02 06:26:39.777064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d9c480c8781'
down_revision: Union[str, None] = '5c63f0455314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('agent', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('capability', sa.String(length=100), nullable=True),
    sa.Column('commit', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('effort', sa.String(length=20), nullable=False),
    sa.Column('cli_version', sa.String(length=100), nullable=True),
    sa.Column('prompt_hash', sa.String(length=32), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('log_path', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('num_turns', sa.Integer(), nullable=False),
    sa.Column('candidates_created', sa.Integer(), nullable=False),
    sa.Column('candidates_rejected', sa.Integer(), nullable=False),
    sa.Column('questions_created', sa.Integer(), nullable=False),
    sa.Column('evidence_rejected', sa.Integer(), nullable=False),
    sa.Column('duplicates_skipped', sa.Integer(), nullable=False),
    sa.Column('potential_duplicates', sa.Integer(), nullable=False),
    sa.Column('workspace_clean', sa.String(length=10), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_runs_source_id'), 'discovery_runs', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovery_runs_source_id'), table_name='discovery_runs')
    op.drop_table('discovery_runs')
    # ### end Alembic commands ###
