"""consumo centralidade e fts

Revision ID: 9e630ee9403e
Revises: 5d9c480c8781
Create Date: 2026-09-02 08:26:16.598243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9e630ee9403e'
down_revision: Union[str, None] = '5d9c480c8781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # busca fuzzy (§53): similaridade de trigram no título
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_knowledge_atoms_title_trgm "
        "ON knowledge_atoms USING gin (title gin_trgm_ops)"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_atoms', sa.Column('centrality', sa.Float(), nullable=True))
    op.add_column('knowledge_atoms', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', coalesce(title,'') || ' ' || coalesce(description,'') || ' ' || coalesce(body->>'statement',''))", persisted=True), nullable=True))
    op.create_index('ix_knowledge_atoms_search', 'knowledge_atoms', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_atoms_search', table_name='knowledge_atoms', postgresql_using='gin')
    op.drop_column('knowledge_atoms', 'search_vector')
    op.drop_column('knowledge_atoms', 'centrality')
    # ### end Alembic commands ###
    op.execute("DROP INDEX IF EXISTS ix_knowledge_atoms_title_trgm")
